cogs:
  general:
    enabled: true
    commands:
      ping: true
  ai:
    enabled: true
    commands:
      chat: true
      image: true
      ocr: true
      translate: true
  logging:
    enabled: true
    commands:
      events: true
  config:
    enabled: true
    commands:
      core: true
