cogs:
  general:
    enabled: true
    commands:
      ping: true # cogs/general/ping.py
  ai:
    enabled: true
    commands:
      chat: true      # cogs/ai/chat.py
      image: true     # cogs/ai/image.py
      ocr: true       # cogs/ai/ocr.py
      translate: true # cogs/ai/translate.py
  moderation:
    enabled: false
    commands:
      actions: false # cogs/moderation/actions.py
  logging:
    enabled: true
    commands:
      events: true   # cogs/logging/events.py
      settings: true # cogs/logging/settings.py